### ISSUE TITLE
Factorials of large numbers 

### ISSUE THREAD

**Issue by jigneshsolanki07** [avinash201199/DSA-Questions#10]
Hello, I am a participant of Hacktoberfest 2021, and I want to add a question related to the number theory .

Factorials of large numbers, Given an integer N, find its factorial.

Example:

Input: N = 5
Output: 120

Explanation : 5! = 1*2*3*4*5 = 120

This problem falls under the category of number theory.

Kindly assign me this issue.

**Comment by avinash201199** [comment]
@jigneshsolanki07  
go ahead :)

**Comment by aniket-24** [comment]
Please assign me this issue!

**Comment by apoorva-raj** [comment]
Please assign me this issue !

**Comment by DoC-CoddER** [comment]
@jigneshsolanki07 please assign this to me

**Comment by avinash201199** [comment]
> Please assign me this issue !

create your own issue.
