### ISSUE TITLE
Find largest rectangle of 0 in Matrix

### ISSUE THREAD

**Issue by 28Pollux28** [avinash201199/DSA-Questions#11]
Hi I'm an Hactoberfest participant and I would like to submit this question that falls under the Matrix category :

Given a Matrix of size (n,n) only composed of 1 and 0, find the coordinates of the largest rectangle only composed of 0.

Kindly assign me this issue.

**Comment by avinash201199** [comment]
@28Pollux28 
Go ahead :)
