### ISSUE TITLE
Spiral Matrix C++

### ISSUE THREAD

**Issue by MeeeCoder** [avinash201199/DSA-Questions#112]
**Question:** Given an m x n matrix, return all elements of the matrix in spiral order.
**Input:**
```
matrix = [[1,2,3],
          [4,5,6],
          [7,8,9]]
```
**Output:**  [1,2,3,6,9,8,7,4,5]
Can I work on this issue, please?

**Comment by MeeeCoder** [comment]
Please assign this issue to me. @avinash201199

**Comment by shubhamnag14** [comment]
can i work in this issue

**Comment by MeeeCoder** [comment]
Closing issue #112 Spiral Matrix
