### ISSUE TITLE
painting the fence - c++

### ISSUE THREAD

**Issue by manognyaa** [avinash201199/DSA-Questions#134]
hello sir!!

I am interested in this problem, I will code in c++. Please assign me this sir. 

problem- Given a fence with n posts and k colors, find out the number of ways of painting the fence such that at most 2 adjacent posts have the same color.  

`@avinash201199 sir` pls kindly assign me this issue

**Comment by avinash201199** [comment]
@manognyaa 
All the best :)
follow me for more such repo to contribute

**Comment by manognyaa** [comment]
> @manognyaa All the best :) follow me for more such repo to contribute

Sure sir. Thank you so much !!

**Comment by avinash201199** [comment]
> > @manognyaa All the best :) follow me for more such repo to contribute
> 
> Sure sir. Thank you so much !!

They are not considering dsa,cp,algorithm repository :(
all the pr will not be considered in hacktoberfest but your contribution will be for lifetime, this will help many students to practice dsa .
Thank you for your contribution :)
you can contribute to other repo
