### ISSUE TITLE
Rotate a matrix clockwise and anti-clockwise | C++

### ISSUE THREAD

**Issue by MeeeCoder** [avinash201199/DSA-Questions#154]
Given a matrix, I will display it after rotating it clockwise and anticlockwise by 90 degrees.
Input:
1 2 3
4 5 6
7 8 9
Output:
Clockwise:
7 4 1
8 5 2
9 6 3
Anti-clockwise:
3 6 9
2 5 8
1 4 7

**Comment by SOURAB-BAPPA** [comment]
I want to solve this problem in C++

**Comment by tausiq2003** [comment]
should I contribute

**Comment by avinash201199** [comment]
\


They are not considering dsa,cp,algorithm repository :(
all the pr will not be considered in hacktoberfest but your contribution will be for lifetime, this will help many students to practice dsa .
Thank you for your contribution :)
you can contribute to other repo
