### ISSUE TITLE
Palindrome Number

### ISSUE THREAD

**Issue by aniket-24** [avinash201199/DSA-Questions#16]
Question-
Given an integer x, return true if x is palindrome integer.
An integer is a palindrome when it reads the same backward as forward. For example, 121 is palindrome while 123 is not.

Example 1:
Input: x = 121
Output: true

Example 2:
Input: x = -121
Output: false
Explanation: From left to right, it reads -121. From right to left, it becomes 121-. Therefore it is not a palindrome.

**Comment by aniket-24** [comment]
Please assign me this issue under Hacktoberfest @avinash201199

**Comment by avinash201199** [comment]
Go ahead :) @aniket-24

**Comment by aniket-24** [comment]
okay :D

**Comment by aniket-24** [comment]
In which folder do I add this Palindrome Number program? @avinash201199

**Comment by DoC-CoddER** [comment]
@avinash201199  can you multiple assign peoples ?

**Comment by avinash201199** [comment]
> @avinash201199 can you multiple assign peoples ?

no , create your own issue .
