### ISSUE TITLE
Length of Last Word in the given String

### ISSUE THREAD

**Issue by sachin4429** [avinash201199/DSA-Questions#180]
Given a string s consisting of some words separated by some number of spaces, return the length of the last word in the string.

A word is a maximal substring consisting of non-space characters only.

 

Example 1:

Input: s = "Hello World"
Output: 5
Explanation: The last word is "World" with length 5.

Example 2:

Input: s = "luffy is still joyboy"
Output: 6
Explanation: The last word is "joyboy" with length 6.
 

Constraints:

1 <= s.length <= 104
s consists of only English letters and spaces ' '.
There will be at least one word in s.

**Comment by sachin4429** [comment]
Can I work in this Issue for Hactoberfest 2021.

**Comment by SB2318** [comment]
I want to work on this using Java language

**Comment by Prabhjout** [comment]
Hi I am a participant of hacktoberfest 2021 Can I work on this Issue I will be solving this issue using java

**Comment by prakharshukla48** [comment]
Hi I am a participant of hacktoberfest 2021 Can I work on this Issue? I will be solving this issue using python.

**Comment by srusti610** [comment]
Hello, I would like to contribute. May I be assigned to this?
