### ISSUE TITLE
Linked List in C

### ISSUE THREAD

**Issue by Masters-Akt** [avinash201199/DSA-Questions#187]
There is no code available for Linked List in C language. I would like to add it.

**Comment by Mohamed-Ayaan358** [comment]
Isn't this a bit generalised?

**Comment by Masters-Akt** [comment]
Since there was no code present, so I generated this issue. Currently added Singly Linked List with all the features. Working on adding more

**Comment by Mohamed-Ayaan358** [comment]
I think you are mistaken i do believe someone has already done singly linked list in c

**Comment by avinash201199** [comment]
@Masters-Akt  this program is already added in c , choose any other language , create another issue , closing this one .
