### ISSUE TITLE
Running Sum of an Array in Java

### ISSUE THREAD

**Issue by SwatiSrivastava216** [avinash201199/DSA-Questions#189]
Write a program that reads an array of nums and outputs the running sum of in the given array of numbers.

Sample Input:
[1,2,3,4]

Sample Output:
[1,3,6,10]

Explanation:
Running sum is obtained as [1, 1+2, 1+2+3, 1+2+3+4]

**Comment by sathiyajith** [comment]
I would like to work on this issue in python language. Let me place the code in array/python directory.
