### ISSUE TITLE
adding bubble sort algorithm in Python & Golang

### ISSUE THREAD

**Issue by andre-fajar-n** [avinash201199/DSA-Questions#20]
Hi, I'm participant of Hacktoberfest '21. I want to add bubble sort algorithm in some different language, such as Golang, Python. Can I create PR one by one based on language?

**Comment by avinash201199** [comment]
@andre-fajar-n  go ahead :)

**Comment by Sanket2055** [comment]
hello , i would like to contribute in c++ lang. please allow me to go ahead

**Comment by 2devyank** [comment]
I want to add bubble sort algorithm in java please assign this to me

**Comment by avinash201199** [comment]
@Sanket2055 create your own issue ,will assing you surely.

**Comment by avinash201199** [comment]
@

> I want to add bubble sort algorithm in java please assign this to me

Create new issue , will assign you.

**Comment by fakeshkol** [comment]
could you please assign me bubble sort in Golang?
