### ISSUE TITLE
Examples programs for linked list and stacks 

### ISSUE THREAD

**Issue by Mohamed-Ayaan358** [avinash201199/DSA-Questions#205]
Hey!
I am Mohamed ayaan and I am a participant registered in Hacktoberfest.
This is my third issue in this repository. I would like to contribute on the topic:-

Example programs(For understanding the implementation) for linked list in C as well as stacks in C
The program includes examples for the topics- having proper comments explaining each part of the code.

Could you please assign this issue to me?
Thank You!

**Comment by avinash201199** [comment]
@Mohamed-Ayaan358  only 2 pull request are accepted in a single repo , please delete extra issue and pr .

**Comment by Mohamed-Ayaan358** [comment]
Could you please specify which ones must I delete?
