### ISSUE TITLE
Single Number | C++

### ISSUE THREAD

**Issue by MeeeCoder** [avinash201199/DSA-Questions#226]
**Question:** Given an array of integers, all the numbers appears twice except one number, we need to find that number.
**Contraints:** Complete it in O(n) time complexity
**Input:** [1, 2, 3, 3, 1, 9, 2]
**Output:** 9

Please allow me to work on this issue @avinash201199 
Thank you

**Comment by avinash201199** [comment]
Note- only 2 pr per day on a single repo is accepted.
