### ISSUE TITLE
DSA - Binary Search Tree in C++

### ISSUE THREAD

**Issue by silicolicious** [avinash201199/DSA-Questions#23]
Hi Avinash Singh!
I am Mageshkrishna R, and I am a participant registered in Hacktoberfest.
I recently started open-source contributions.
I am good in DSA and I would like to contribute on the topic:- 
- *Binary Search Tree* in C++ language.  

The program would include Insertion, Deletion and Searching - with proper comments explaining each part of the code.

Thank You!

**Comment by avinash201199** [comment]
@silicolicious  go ahead :) 
Follow  for more updates -https://github.com/avinash201199
