### ISSUE TITLE
Shortest Subarray with Sum at Least K 

### ISSUE THREAD

**Issue by SB2318** [avinash201199/DSA-Questions#242]
I am Susmita Bhattacharya, and I am participating in Hacktoberfest 2021.
I am totally new and noob in open-source contributions.
I would like to contribute on this topic. It is a leetcode question and  I want to solve it in Java language. Please assign it to me.

###  **Question:**
Given an integer array nums and an integer k, return the length of the shortest non-empty subarray of nums with a sum of at least k. If there is no such subarray, return -1.
A subarray is a contiguous part of an array.

### **Example 1:**
`Input : [2,-1,2] , k=3`
`Output: 3`

### **Example 2:**
`Input : [1,2] , k=4`
`Output: -1`

### **Constraints:**
` 1 <= nums.length <= 10^5`
`-10^5 <= nums[i] <= 10^5`
 ` 1 <= k <= 10^9`

**Comment by SB2318** [comment]
Please assign it to me.

**Comment by SB2318** [comment]
Thank you very much for accepting my issue. 
Can you please tell me the time limit of submitting it?

**Comment by avinash201199** [comment]
hey , they are not considering dsa,cp and algorithm repo
but you can contribute to this repo as a part of community :)
this will help many students to practice dsa

**Comment by SB2318** [comment]
Okay, Thanks for merging it.😇
