### ISSUE TITLE
Dynamic Programming: Climbing Stairs

### ISSUE THREAD

**Issue by pradyyadav** [avinash201199/DSA-Questions#262]
Hi, I have my code written for this issue. Please assign it to me.

**Comment by Prince-ranjan** [comment]
Hello, i have written the codes for this problem using recursion, memoization with recursion, and dynamic programming. Please assign me this problem under hacktoberfest tag

**Comment by avinash201199** [comment]
> Hello, i have written the codes for this problem using recursion, memoization with recursion, and dynamic programming. Please assign me this problem under hacktoberfest tag

create your own and specify the language will assign you.
