### ISSUE TITLE
Program to find the number of lines,words and characters in a .txt file using Python

### ISSUE THREAD

**Issue by mayankgoyal-13** [avinash201199/DSA-Questions#266]

**Comment by mayankgoyal-13** [comment]
Hey, i would like to submit this program using the Python language. Pls assign this to me, this is my first issue today

**Comment by akshitaPrajapati** [comment]
Hey, Avinash.
Could you  please assign me this task, so I could contribute to it?

**Comment by avinash201199** [comment]
> Hey, Avinash. Could you please assign me this task, so I could contribute to it?

please create your own issue ,will surely assign you :)

**Comment by mayankgoyal-13** [comment]
@avinash201199 I have created the pull request #410 for this code and pls label that pr as hacktoberfest.
