### ISSUE TITLE
Adding DP problem of Maximal Square

### ISSUE THREAD

**Issue by vishakha-aggarwal** [avinash201199/DSA-Questions#270]
I would like to add this problem in DP folder of C++.

**Problem:** 
Given an m X n binary matrix filled with only 0's and 1's, Find the largest square containing only 1's and return its area.

**Example:** 

Let Matrix be:
1,0,**1,1**,1
1,1,**1,1**,1
1,0,0,1,0

So, the maximum area of the square would be : 4

Kindly assign me this issue. 
Please tag this issue with 'hacktoberfest 2021'.

**Comment by vishakha-aggarwal** [comment]
PR merged successfully

**Comment by avinash201199** [comment]
They are not considering dsa,cp,algorithm repository :(
all the pr will not be considered in hacktoberfest but your contribution will be for lifetime, this will help many students to practice dsa .
Thank you for your contribution :)
you can contribute to other repo
