### ISSUE TITLE
Stack Program

### ISSUE THREAD

**Issue by ZeelParekh10** [avinash201199/DSA-Questions#271]
I would like to add Code of Stack...........
language: C
Implement a program for stack that performs following operations using array.
(a) PUSH (b) POP (c) PEEP (d) CHANGE (e) DISPLAY

Please assign me this issue.
Tag Hacktomber fest also.
Thank You !!!

**Comment by rajputarjun2001** [comment]
Hi @ZeelParekh10 could you please assign this to me?
