### ISSUE TITLE
Addition of concept of Disjoint Set Union.

### ISSUE THREAD

**Issue by khushbooSingh99** [avinash201199/DSA-Questions#274]
Addition of DSU concept.

Often it is also called Union Find because of its two main operations.

**I want to add a text file for the implementation details as well as,
I will add a question that involves this concept,**

Please accept my improvement. @avinash201199 , and assign me this issue.

**Comment by khushbooSingh99** [comment]
I have posted the corresponding PR for this.

**Comment by avinash201199** [comment]
> Addition of DSU concept.
> 
> Often it is also called Union Find because of its two main operations.
> 
> **I want to add a text file for the implementation details as well as, I will add a question that involves this concept,**
> 
> Please accept my improvement. @avinash201199 , and assign me this issue.

@khushbooSingh99 
Great :)
