### ISSUE TITLE
DSA- Linked List in C++

### ISSUE THREAD

**Issue by VaibhavMogha** [avinash201199/DSA-Questions#28]
# Hi Avinash!
I am Vaibhav, and I am participating in Hacktoberfest 2021.
I am totally new and noob in open-source contributions.
I would like to contribute on this topic:

**Linked List in C++ language.**

Please assign me this.
Thank You!

**Comment by avinash201199** [comment]
Go ahead @VaibhavMogha 
follow for more updates-https://github.com/avinash201199

**Comment by VaibhavMogha** [comment]
Please review #106 and review it.
