### ISSUE TITLE
Adding Java Squares of a Sorted Array

### ISSUE THREAD

**Issue by MasterBrian99** [avinash201199/DSA-Questions#3]
Question-Given an array of numbers sorted in increasing order, return a new array containing squares of all the numbers of the input array sorted in increasing order.
Example- Input: arr[] = [-5, -2, -1, 0, 4, 6]

Output: [0, 1, 4, 16, 25, 36]

**Comment by avinash201199** [comment]
Go ahead @MasterBrian99  
Are you a participant of Hacktoberfest?

**Comment by MasterBrian99** [comment]
yeah..

**Comment by avinash201199** [comment]
Okay , add your program and make  pull request will accept on 1 October fo successful count.

**Comment by MasterBrian99** [comment]
i just realized,it hasn't even started yet.anyway,i will make another request when it started.btw can we add javascript language also ?

**Comment by avinash201199** [comment]
Will accept your this pull request on 1st october then you will get 1 successful pull request. Yeah you can add javascript programs. First make folder of javascript inside the topic and then add your programs.
