### ISSUE TITLE
DSA - Singly Linked List in C

### ISSUE THREAD

**Issue by silicolicious** [avinash201199/DSA-Questions#31]
Hi!
I am Mageshkrishna R, and I am a participant registered in Hacktoberfest.
This is my second issue in this repository. I would like to contribute on the topic:-
- Singly Linked List in C language.

The program would include Insertion, Deletion and Searching - having proper comments explaining each part of the code.

Assign this issue to me.
Thank You!

**Comment by avinash201199** [comment]
Go ahead @silicolicious

**Comment by tausiq2003** [comment]
should I contribute
