### ISSUE TITLE
Matrix Multiplication Using Java Python and C++

### ISSUE THREAD

**Issue by RahulSharma4329** [avinash201199/DSA-Questions#314]
Question - given two matrices of size m x n and p x q, find the product matrix of the given matrices.
Please assign me this issue under the tag of hacktober fest @avinash201199

**Comment by srusti610** [comment]
Hello ,I would like to contribute. May I be assigned to this?

**Comment by CyberSkull1243** [comment]
Hello sir can you please assign this task to me. I would like to contribute in this.

**Comment by avinash201199** [comment]
They are not considering dsa,cp,algorithm repository :(
all the pr will not be considered in hacktoberfest but your contribution will be for lifetime, this will help many students to practice dsa .
Thank you for your contribution :)
you can contribute to other repo
