### ISSUE TITLE
DSA - Matrix in C++

### ISSUE THREAD

**Issue by VaibhavMogha** [avinash201199/DSA-Questions#33]
# Hi Avinash!
I am Vaibhav, and I am participating in Hacktoberfest 2021.
I am totally new and noob in open-source contributions.
I would like to contribute on this topic:

**Matrix in C++ language with theory.**

Please assign me this.
Thank You!

**Comment by Swapna804** [comment]
I am participating in hacktoberfest and would like to contribute .Please assign it.
