### ISSUE TITLE
Find in Mountain Array

### ISSUE THREAD

**Issue by 2000shivam659** [avinash201199/DSA-Questions#337]
## Link of the question
https://leetcode.com/problems/find-in-mountain-array/
<img width="957" alt="cd" src="https://user-images.githubusercontent.com/76156804/135704568-fc55c311-c92c-4ce3-93eb-9698ed6a8374.png">

## Coding platform

- [ ] Hackerrank
- [ ] HackerEarth
- [ ] Codechef
- [ ] Codeforces
- [x] Leetcode
- [ ] InterviewBit
- [ ] AtCoder
- [ ] 450 DSA Sheet
## Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python.

**Comment by 2000shivam659** [comment]
Kindly assign me this issue @avinash201199 under Hacktoberfest'21.

**Comment by avinash201199** [comment]
@2000shivam659 
don't forget to add problem statement on the code file :)
