### ISSUE TITLE
Sorting Methods

### ISSUE THREAD

**Issue by ZeelParekh10** [avinash201199/DSA-Questions#341]
I would like To add codes of some sorting methods in Search and Sort folder.
language: C
Sorting Methods:
Bubble Sort
Selection Sort 
QuickSort

Would also like to change the name of the folder as i think there is a typo in the name of the folder.

Iam a Hacktomber Fest Participant..........

**Comment by avinash201199** [comment]
@ZeelParekh10 
don't forget to add problem statement.

**Comment by ZeelParekh10** [comment]
> @ZeelParekh10 don't forget to add problem statement.

Okay !!!!

**Comment by ZeelParekh10** [comment]
https://github.com/avinash201199/DSA-Questions/commit/1686bb090701ad564194319818a87be116ed4125
