### ISSUE TITLE
Pair Sum Problem Optimized

### ISSUE THREAD

**Issue by rnrathod16** [avinash201199/DSA-Questions#350]
Hi, I am a participant of Hacktoberfest. I would like to add this question of pair sum which can be solved with the help of sets. Kindly assign me this issue under hacktoberfest. Thank you.
Question:
Find the pair which gives the sum same as assigned number

Input:  [1,4,6,2,5,3,0]
n=3
Output: [1,2]

**Comment by Amitlpu-840** [comment]
Hii. please assign this to me. I will solve this issue as I am experienced in c++.
