### ISSUE TITLE
Reverse K Nodes in Linked List

### ISSUE THREAD

**Issue by rnrathod16** [avinash201199/DSA-Questions#364]
Hi, I am a participant of Hacktoberfest. I would like to add this question of reversing the linked list after every k given. Kindly assign me this issue under hacktoberfest. Thank you.
Question:
Write a code to reverse linked list after every k nodes

Input = 1->2->3->4->5->6->7->8->NULL
k=3
Output = 3->2->1->6->5->4->8->7->NULL

**Comment by esheetaparulekar** [comment]
Hello, can I work on this issue in Java?

**Comment by avinash201199** [comment]
> Hello, can I work on this issue in Java?

go ahead :)
