### ISSUE TITLE
Stock Span Problem in C++

### ISSUE THREAD

**Issue by anushkadubey** [avinash201199/DSA-Questions#365]
The stock span problem is a financial problem where we have a series of n daily price quotes for a stock and we need to calculate the span of stock’s price for all n days. 
The span Si of the stock’s price on a given day i is defined as the maximum number of consecutive days just before the given day, for which the price of the stock on the current day is less than or equal to its price on the given day.
For example, if an array of 7 days prices is given as {100, 80, 60, 70, 60, 75, 85}, then the span values for corresponding 7 days are {1, 1, 1, 2, 1, 4, 6}.

**Example 1:**
_Input:_ 
N = 7, price[] = [100 80 60 70 60 75 85]
_Output:_
1 1 1 2 1 4 6
_Explanation:_
Traversing the given input span for 100 
will be 1, 80 is smaller than 100 so the 
span is 1, 60 is smaller than 80 so the 
span is 1, 70 is greater than 60 so the 
span is 2 and so on. Hence the output will 
be 1 1 1 2 1 4 6.

**Example 2:**
_Input:_ 
N = 6, price[] = [10 4 5 90 120 80]
_Output:_
1 1 2 4 5 1
_Explanation:_
Traversing the given input span for 10 
will be 1, 4 is smaller than 10 so the 
span will be 1, 5 is greater than 4 so 
the span will be 2 and so on. Hence, the 
output will be 1 1 2 4 5 1.

**Expected Time Complexity**: O(N).
**Expected Auxiliary Space**: O(N).

**Constraints:**
1 ≤ N ≤ 105
1 ≤ C[i] ≤ 105

**Comment by shafi9155** [comment]
Please assigned me this issue I can solve it

**Comment by anushkadubey** [comment]
@shafi9155 I have already solved it, I am just waiting for it to be assigned to me.

**Comment by avinash201199** [comment]
> Please assigned me this issue I can solve it

create your own issue

**Comment by avinash201199** [comment]
> @shafi9155 I have already solved it, I am just waiting for it to be assigned to me.

don't worry will accept you soon
for immediate contact ping me here -https://www.instagram.com/lets__code/

**Comment by anushkadubey** [comment]
Okay, thanks!:) @avinash201199

**Comment by avinash201199** [comment]
@anushkadubey 
They are not considering dsa,cp,algorithm repository :(
all the pr will not be considered in hacktoberfest but your contribution will be for lifetime, this will help many students to practice dsa .
Thank you for your contribution :)
you can contribute to other repo
