### ISSUE TITLE
Add Mahasena.cpp

### ISSUE THREAD

**Issue by sej28** [avinash201199/DSA-Questions#374]
Question
Kattapa, as you all know was one of the greatest warriors of his time. The kingdom of Maahishmati had never lost a battle under him (as army-chief), and the reason for that was their really powerful army, also called as Mahasena.

Kattapa was known to be a very superstitious person. He believed that a soldier is "lucky" if the soldier is holding an even number of weapons, and "unlucky" otherwise. He considered the army as "READY FOR BATTLE" if the count of "lucky" soldiers is strictly greater than the count of "unlucky" soldiers, and "NOT READY" otherwise.

Given the number of weapons each soldier is holding, your task is to determine whether the army formed by all these soldiers is "READY FOR BATTLE" or "NOT READY".

Link to the question
https://www.codechef.com/problems/AMR15A

**Comment by sej28** [comment]
pls assign this to me

**Comment by avinash201199** [comment]
@sej28 don't forget to add problem statement in the code

**Comment by sej28** [comment]
before the code itself right?

**Comment by avinash201199** [comment]
They are not considering dsa,cp,algorithm repository :(
all the pr will not be considered in hacktoberfest but your contribution will be for lifetime, this will help many students to practice dsa .
Thank you for your contribution :)
