### ISSUE TITLE
Longest Band

### ISSUE THREAD

**Issue by rnrathod16** [avinash201199/DSA-Questions#376]
Hi, I am a participant of Hacktoberfest. I would like to add this question of finding the longest band. Kindly assign me this issue under hacktoberfest. Thank you.
Question: 
Write code to find the largest subset  containing consecutive numbers.

Input  = [ 1,9,3,0,18,5,2,4,10,7,12,6 ]
Output = 8

Explanation : -  Largest subset containing consecutive number is [ 0,1,2,3,4,5,6,7 ]

**Comment by avinash201199** [comment]
@rnrathod16  only 2 issue per day :)
complete the 2 first , closing the issue
