### ISSUE TITLE
Grammatical error in readme

### ISSUE THREAD

**Issue by pranav-git-hub** [avinash201199/DSA-Questions#40]
Hi, 
I am participating in Hacktoberfest2021.
I want to fix the grammatical error in the readme file.
Regards.

**Comment by avinash201199** [comment]
Can you list the grammatical error's ?

**Comment by pranav-git-hub** [comment]
I will create a pull request in which you can see the changes and verify them.

**Comment by pranav-git-hub** [comment]
I have created the request.
