### ISSUE TITLE
Reverse a linked list

### ISSUE THREAD

**Issue by ritish1082** [avinash201199/DSA-Questions#411]
Hi!
My name is Sai Ritish and I am a registered participant of hacktoberfest.

The above issue will be dealing with reversing a linked list recursively using c language.

**Comment by avinash201199** [comment]
They are not considering dsa,cp,algorithm repository :(
all the pr will not be considered in hacktoberfest but your contribution will be for lifetime, this will help many students to practice dsa .
Thank you for your contribution :)

**Comment by avinash201199** [comment]
you can contribute to other repo also
