### ISSUE TITLE
Palindrome using stacks

### ISSUE THREAD

**Issue by ritish1082** [avinash201199/DSA-Questions#413]
Hi!
In the above issue by using the concept of stacks we can check whether string is palindrome or not.
Please can you assign me the issue. @avinash201199

**Comment by avinash201199** [comment]
They are not considering dsa,cp,algorithm repository :(
all the pr will not be considered in hacktoberfest but your contribution will be for lifetime, this will help many students to practice dsa .
Thank you for your contribution :)

**Comment by Rohit5152** [comment]
He bro please assign this problem to me .
Because i already solved this

**Comment by ritish1082** [comment]
Added to the repository successfully!
