### ISSUE TITLE
Sieve of Eratosthenes using C++

### ISSUE THREAD

**Issue by Anant-mishra1729** [avinash201199/DSA-Questions#430]
Sieve of Eratosthenes algorithm for finding prime numbers less than or equal to given number

**Comment by avinash201199** [comment]
They are not considering dsa,cp,algorithm repository :(
all the pr will not be considered in hacktoberfest but your contribution will be for lifetime, this will help many students to practice dsa .
Thank you for your contribution :)
you can contribute to other repo
