### ISSUE TITLE
Add "Triplet Sum in Array" question

### ISSUE THREAD

**Issue by ssm0801** [avinash201199/DSA-Questions#5]
**Statement** : Given array of size n and an integer T. Find triplet in the array which sums up to the given integer T.

**Input :**
```python
n = 6
T = 13
arr[] = [1 4 45 6 10 8]
``` 

**Output :**
```python
[1, 4, 8]
```

**Comment by avinash201199** [comment]
@ssm0801 Go ahead 😃
