### ISSUE TITLE
largest sum contiguous Subarray

### ISSUE THREAD

**Issue by SanskritiKhatiyan** [avinash201199/DSA-Questions#61]
@avinash201199 Hey!! I want to add one array question of finding Largest sum subarray question.
  Here, I will explain kadane's algorithm approach. I guess this question is important.

Can you assign a hacktoberfest label and assign it to me.

**Comment by avinash201199** [comment]
Go ahead :)  @SanskritiKhatiyan

**Comment by SanskritiKhatiyan** [comment]
@avinash201199 hey!! plz review it and plzz merge it if it is fine otherwise tell me what to improve.
