### ISSUE TITLE
Maximum Gap

### ISSUE THREAD

**Issue by Khushi-Agrawal-1** [avinash201199/DSA-Questions#62]
Hi @avinash201199

I would like to add a program to return the maximum difference between two successive elements in an integer array.

Can you assign a 'hacktoberfest' label and assign it to me?

Thanks

**Comment by avinash201199** [comment]
@Khushi-Agrawal-1  
All the best :)

**Comment by 2000shivam659** [comment]
Hey, kindly assign me this in java language under Hacktoberfest'21.

**Comment by Khushi-Agrawal-1** [comment]
@2000shivam659 I have been assigned this and I'll be doing this in Java only. Thankyou

**Comment by 2000shivam659** [comment]
> @2000shivam659 I have been assigned this and I'll be doing this in Java only. Thankyou

Ofcourse, but you didn't mention the language which you will use. This problem can be solved in different languages in many ways.

**Comment by Khushi-Agrawal-1** [comment]
Sure

**Comment by Khushi-Agrawal-1** [comment]
@avinash201199 I have made a PR. Kindly review it. Thank you
