### ISSUE TITLE
Bit Manipulation

### ISSUE THREAD

**Issue by arjun-khanduri** [avinash201199/DSA-Questions#63]
Hey @avinash201199!

I would like to add the program: __Finding the square of a number without using the *, ** operators or the pow function.__

Can you assign a `hacktoberfest` label and assign it to me?

**Comment by avinash201199** [comment]
@avinash201199  go ahead :)

**Comment by arjun-khanduri** [comment]
@avinash201199 I have made the pull request. Can you check if it is good enough to be merged?
