### ISSUE TITLE
First Unique Charachter of a string

### ISSUE THREAD

**Issue by ASLManasa** [avinash201199/DSA-Questions#7]
Hi, I am a participant of Hacktoberfest. I would like to add this question in strings. Kindly assign me this issue. Thank you.

Question: Given a string s, find the first non-repeating character in it and return its index. If it does not exist, return -1.

Input: s = "aabb"
Output: -1
Input: s = "code"
Output: 0

**Comment by vish-han** [comment]
Can i do this plzz assign me , I will be very grateful....

**Comment by ZeelParekh10** [comment]
Plz, Assign me i have the solution ready

**Comment by avinash201199** [comment]
@ASLManasa 
Go ahead :)

**Comment by avinash201199** [comment]
@ZeelParekh10  Create your own issue will assign you surely :)
