### ISSUE TITLE
Python : Next number of the look-and-say sequence

### ISSUE THREAD

**Issue by 28Pollux28** [avinash201199/DSA-Questions#72]
Hi, I'm an Hacktober participant and I'd like to contribute on the Number Theory topic :
Given a positive integer, return the next number in the look-and-say sequence.
For example : 25447 ->12152417
Kindly assign me this issue.

**Comment by avinash201199** [comment]
@28Pollux28  Will assign this issue once your first issue is completed.

**Comment by 28Pollux28** [comment]
All done ! Can you assign it to me ?
