### ISSUE TITLE
Rotate array 

### ISSUE THREAD

**Issue by ritika728** [avinash201199/DSA-Questions#76]
QUESTION: Given an unsorted array ar of size n and an element k. Rotate the array by k elements in anti-clockwise direction.

**Comment by ritika728** [comment]
Hey!
I am quite new to open source and would like to contribute on this issue. Please assign it to me and add the tag of Hacktoberfest.

**Comment by avinash201199** [comment]
All the best @ritika728 
for any doubt ping me here -https://www.instagram.com/lets__code/

**Comment by ritika728** [comment]
> All the best @ritika728 
> for any doubt ping me here -https://www.instagram.com/lets__code/

Sure, thank you!
