### ISSUE TITLE
Solution of the DSA question

### ISSUE THREAD

**Issue by ZeelParekh10** [avinash201199/DSA-Questions#8]
Hii, Iam a newbie..... just starting the contribution journey............... learning new things, well this is my first issue.before this i didnt even know how to create issues, so this is the code ......................

Language used: Python

from collections import Counter
str=input()
count=Counter(str)
for i in str:
    if count[i]==1:
        index_of=i
        break
    else:
        index_of=-1

print(-1) if index_of==-1 else print(str.index(index_of))

**Comment by avinash201199** [comment]
@ZeelParekh10 Go ahead, while adding please be more descriptive about the program.
for example 
![image](https://user-images.githubusercontent.com/61057666/135282282-dab547c5-17ce-48f2-8475-7f3ab4a88ba8.png)

**Comment by ZeelParekh10** [comment]
Okay, will note the point down !!!

> @ZeelParekh10 Go ahead, while adding please be more descriptive about the program. for example ![image](https://user-images.githubusercontent.com/61057666/135282282-dab547c5-17ce-48f2-8475-7f3ab4a88ba8.png)

**Comment by ZeelParekh10** [comment]
"""
Question: Given a string s, find the first non-repeating character in it and return its index. If it does not exist, return -1.

Input: s = "aabb"
Output: -1
Input: s = "code"
Output: 0

Language used: Python

Here we will simply use Counter that will help us in counting the elements of the string.
Then we will run a loop that will run till we find the first non-repeating character
"""

![ghq](https://user-images.githubusercontent.com/90596719/135287370-9a7faf21-5d90-4368-8508-c0e16cb7fc91.jpg)

**Comment by aniket-24** [comment]
Please assign me this issue!

**Comment by avinash201199** [comment]
@ZeelParekh10  add your program

**Comment by ZeelParekh10** [comment]
> @ZeelParekh10 add your program

Can you explain me what should be done after creating an issue, do i have to pull a request or something else
