### ISSUE TITLE
Infix to Postfix Operation using Stacks Implementation in C

### ISSUE THREAD

**Issue by mukunddeepak** [avinash201199/DSA-Questions#84]
Hey Avinash, Mukund here!
I'd like to implement converting an infix operation to postfix operations using Stacks in C programming language.
Please give approval so that i can start at the earliest!

Please consider this under hacktoberfest!
Regards,
Mukund Deepak

**Comment by avinash201199** [comment]
Go ahead :) @mukunddeepak
