### ISSUE TITLE
Pascal's Triangle

### ISSUE THREAD

**Issue by JyotimoyKashyap** [avinash201199/DSA-Questions#9]
Hello, I am participant of Hacktoberfest 2021, and I want to add a question related to Dynamic Programming.

Given an integer rowIndex, return the rowIndexth (0-indexed) row of Pascal's triangle.

In **Pascal's triangle**, each number is the sum of the two numbers directly above it as shown.
![pascal triangle](https://user-images.githubusercontent.com/55136058/135280606-6a98a550-32cd-4944-af69-ebfe910b00fd.png)
n:

Sample Input: 
Input : rowIndex = 3
Output : [1, 3, 3, 1]

This problem falls under the category of Dynamic Programming. 

Kindly assign me this issue.

**Comment by aniket-24** [comment]
Please assign me this issue!
