### ISSUE TITLE
Game with nos [array and bit magic]

### ISSUE THREAD

**Issue by ritika728** [avinash201199/DSA-Questions#99]
Given an array ar[], need to re-construct this array. The values in reconstructed array are obtained by doing Xor of consecutive elements in the array ar[]. I will solve this in C++.

**Comment by ritika728** [comment]
@avinash201199 Please assign me this!

**Comment by avinash201199** [comment]
> @avinash201199 Please assign me this!

Will assign you , wait for the first one to be merged.

**Comment by ritika728** [comment]
> > @avinash201199 Please assign me this!
> 
> Will assign you , wait for the first one to be merged.

alright!

**Comment by ritika728** [comment]
@avinash201199 Please assign this!
